"""
ThreatSight — Module 4: Respond & Report
==========================================
Generates:
  - SOAR-style automated playbooks per attack type
  - Sigma rules (proper YAML format)
  - Full HTML investigation report
  - JSON export for SIEM ingestion
  - Plain-text executive summary

Author: Krutika Jagdale
"""

import json
from datetime import datetime, timezone
from pathlib import Path

# ── SOAR Playbooks ───────────────────────────────────────────────────────────
PLAYBOOKS = {
    "Brute Force / Credential Attack": [
        "1. Block source IP at perimeter firewall for 24 hours.",
        "2. Lock targeted user account pending investigation.",
        "3. Review authentication logs for last 7 days from same source.",
        "4. Check for successful logon from same IP (T1078 follow-on).",
        "5. Notify account owner and require MFA re-enrollment.",
        "6. Escalate to Tier 2 if >5 unique accounts targeted.",
    ],
    "Privilege Escalation": [
        "1. Terminate active session immediately.",
        "2. Snapshot system state for forensic preservation.",
        "3. Review /var/log/auth.log and /var/log/sudo.log.",
        "4. Check for new cron jobs, services, or SUID binaries created.",
        "5. Revoke escalated privileges and reset account credentials.",
        "6. Escalate to IR team — treat as active compromise.",
    ],
    "Malware / C2 Download": [
        "1. Quarantine host from network immediately.",
        "2. Preserve memory dump and disk image.",
        "3. Identify and block C2 destination at DNS and firewall.",
        "4. Scan all hosts on same subnet for similar activity.",
        "5. Submit payload hash to VirusTotal / threat intel platform.",
        "6. Initiate full IR engagement — do not attempt manual cleanup.",
    ],
    "Web Application Attack": [
        "1. Block source IP at WAF and load balancer.",
        "2. Review all requests from this IP in last 24 hours.",
        "3. Check application logs for successful exploitation indicators.",
        "4. Notify application owner and development team.",
        "5. Run vulnerability scan on affected endpoint.",
        "6. Review WAF rule coverage and update signatures.",
    ],
    "Prompt Injection": [
        "1. Block query at AI gateway layer.",
        "2. Log full prompt and session context for review.",
        "3. Review user's recent interaction history.",
        "4. Check if system prompt was exposed in any response.",
        "5. Update prompt injection filter patterns.",
        "6. Notify AI platform security team.",
    ],
    "Scheduled Task Persistence": [
        "1. Delete suspicious scheduled task immediately.",
        "2. Review task content and execution history.",
        "3. Check for similar tasks across all systems.",
        "4. Investigate account that created the task.",
        "5. Scan for associated malware or scripts.",
        "6. Review privileged account usage in surrounding timeframe.",
    ],
    "Defense Evasion": [
        "1. Re-enable disabled security controls immediately.",
        "2. Alert SOC lead — this indicates active post-compromise activity.",
        "3. Audit which controls were disabled and for how long.",
        "4. Review all activity from source account in last 4 hours.",
        "5. Check for concurrent exfiltration or lateral movement.",
        "6. Initiate full IR engagement.",
    ],
    "default": [
        "1. Document the alert with full context.",
        "2. Verify whether activity is authorized.",
        "3. Escalate to Tier 2 analyst if unauthorized.",
        "4. Block source if confirmed malicious.",
        "5. Update detection rules to improve precision.",
    ],
}

def get_playbook(attack_type: str) -> list:
    return PLAYBOOKS.get(attack_type, PLAYBOOKS["default"])


# ── Sigma Rule Generator ─────────────────────────────────────────────────────
def generate_sigma_rules(findings: list) -> str:
    anomalous = [f for f in findings if f.get("is_anomalous")]
    if not anomalous:
        return "# No anomalous findings — no Sigma rules generated.\n"

    seen = set()
    rules = []
    for f in anomalous:
        title = f.get("sigma_title") or f.get("attack_type","Unknown")
        if title in seen:
            continue
        seen.add(title)
        techniques = f.get("mitre_techniques", [])
        mitre_block = "\n".join(f"        - {t}" for t in techniques) if techniques else "        - T0000"
        rule = f"""---
title: {title}
id: threatsight-{hash(title) & 0xFFFFFF:06x}
status: experimental
description: >
    Detects {f.get('attack_type','unknown attack')} based on ThreatSight analysis.
    Generated by ThreatSight v2.0 | Author: Krutika Jagdale
references:
    - https://attack.mitre.org/techniques/{techniques[0].replace('.','/')+'/' if techniques else ''}
author: Krutika Jagdale
date: {datetime.now(timezone.utc).strftime('%Y/%m/%d')}
tags:
    - attack.{f.get('category','security').lower().replace(' ','_')}
{mitre_block}
logsource:
    product: windows
    service: security
detection:
    selection:
        query|contains:
            - '{f.get('attack_type','').lower()}'
    condition: selection
falsepositives:
    - Legitimate administrative activity
    - Security testing and pen testing
level: {f.get('risk_level','medium')}
"""
        rules.append(rule)
    return "\n".join(rules)


# ── HTML Report ──────────────────────────────────────────────────────────────
def generate_html_report(findings, correlation, stats, output_path):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    anomalous = [f for f in findings if f.get("is_anomalous")]

    RISK_COLORS = {
        "critical": "#dc2626", "high": "#ea580c",
        "medium": "#d97706", "low": "#16a34a", "none": "#6b7280",
    }

    def risk_badge(level):
        color = RISK_COLORS.get(level, "#6b7280")
        return f'<span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:bold">{level.upper()}</span>'

    finding_rows = ""
    for f in findings:
        if not f.get("is_anomalous"):
            continue
        playbook_steps = "".join(f"<li>{s}</li>" for s in get_playbook(f.get("attack_type","")))
        tech_tags = " ".join(f'<code style="background:#e2e8f0;padding:1px 4px;border-radius:3px">{t}</code>' for t in f.get("mitre_techniques",[]))
        finding_rows += f"""
        <div style="border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin-bottom:16px;border-left:4px solid {RISK_COLORS.get(f.get('risk_level','none'),'#6b7280')}">
            <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
                <h3 style="margin:0;font-size:16px">{f.get('attack_type','Unknown')} — Query {f.get('query_id','')}</h3>
                {risk_badge(f.get('risk_level','none'))}
            </div>
            <table style="width:100%;font-size:13px;border-collapse:collapse">
                <tr><td style="color:#6b7280;width:120px">Time</td><td>{f.get('timestamp','')}</td></tr>
                <tr><td style="color:#6b7280">User</td><td>{f.get('user','')}</td></tr>
                <tr><td style="color:#6b7280">Source IP</td><td>{f.get('source_ip','')}</td></tr>
                <tr><td style="color:#6b7280">Category</td><td>{f.get('category','')}</td></tr>
                <tr><td style="color:#6b7280">MITRE</td><td>{tech_tags}</td></tr>
                <tr><td style="color:#6b7280">Reasoning</td><td>{f.get('reasoning','')}</td></tr>
                <tr><td style="color:#6b7280">Rule</td><td>{f.get('detection_rule','')}</td></tr>
            </table>
            <details style="margin-top:12px">
                <summary style="cursor:pointer;color:#3b82f6;font-size:13px">▶ Response Playbook</summary>
                <ol style="font-size:13px;margin-top:8px">{playbook_steps}</ol>
            </details>
        </div>"""

    kc_rows = ""
    for step in correlation.get("kill_chain",[]):
        kc_rows += f"<tr><td>{step['step']}</td><td>{step['tactic']}</td><td>{step['attack_type']}</td><td>{step['timestamp']}</td></tr>"

    ip_rows = ""
    for cluster in correlation.get("ip_clusters",[]):
        ip_rows += f"<tr><td>{cluster['source_ip']}</td><td>{cluster['event_count']}</td><td>{', '.join(cluster['attack_types'])}</td><td>{risk_badge(cluster['risk'])}</td></tr>"

    campaign = correlation.get("campaign") or {}

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ThreatSight Security Report — {now}</title>
<style>
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:24px;background:#f8fafc;color:#1e293b}}
  .card{{background:white;border-radius:12px;padding:24px;margin-bottom:24px;box-shadow:0 1px 3px rgba(0,0,0,.1)}}
  .stat-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}}
  .stat{{background:white;border-radius:8px;padding:20px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,.1)}}
  .stat-number{{font-size:36px;font-weight:700}}
  .stat-label{{font-size:13px;color:#6b7280;margin-top:4px}}
  table{{width:100%;border-collapse:collapse;font-size:13px}}
  th{{background:#f1f5f9;padding:8px 12px;text-align:left;font-weight:600}}
  td{{padding:8px 12px;border-bottom:1px solid #f1f5f9}}
  h1{{font-size:24px;margin:0}} h2{{font-size:18px;margin-bottom:16px}}
  .alert-box{{border-radius:8px;padding:16px;margin-bottom:16px}}
</style>
</head>
<body>
<div style="max-width:1100px;margin:0 auto">

<div class="card" style="border-top:4px solid #3b82f6">
  <div style="display:flex;justify-content:space-between;align-items:center">
    <div>
      <h1>🛡️ ThreatSight Security Report</h1>
      <p style="margin:4px 0;color:#6b7280">Generated: {now} | Author: Krutika Jagdale</p>
    </div>
    <div style="text-align:right;font-size:13px;color:#6b7280">
      ThreatSight v2.0<br>End-to-End Cybersecurity Platform
    </div>
  </div>
</div>

{"" if not campaign.get("detected") else f'''
<div class="alert-box" style="background:#fef2f2;border:1px solid #fecaca;border-left:4px solid #dc2626">
  <strong style="color:#dc2626">⚠ CAMPAIGN ALERT ({campaign.get('confidence','').upper()} CONFIDENCE)</strong>
  <p style="margin:4px 0;font-size:14px">{campaign.get('description','')}</p>
  <p style="margin:4px 0;font-size:13px;color:#6b7280">{campaign.get('recommendation','')}</p>
</div>'''}

<div class="stat-grid">
  <div class="stat"><div class="stat-number" style="color:#3b82f6">{stats['total']}</div><div class="stat-label">Events Analyzed</div></div>
  <div class="stat"><div class="stat-number" style="color:#dc2626">{stats['anomalous']}</div><div class="stat-label">Threats Detected</div></div>
  <div class="stat"><div class="stat-number" style="color:#16a34a">{stats['clean']}</div><div class="stat-label">Clean Events</div></div>
  <div class="stat"><div class="stat-number" style="color:#ea580c">{len(correlation.get('kill_chain',[]))}</div><div class="stat-label">Kill Chain Steps</div></div>
</div>

<div class="card">
  <h2>🔗 Kill Chain Reconstruction</h2>
  {"<p style='color:#6b7280'>No kill chain detected.</p>" if not correlation.get('kill_chain') else f"""
  <table><tr><th>Step</th><th>Tactic</th><th>Attack Type</th><th>Timestamp</th></tr>{kc_rows}</table>"""}
</div>

<div class="card">
  <h2>🎯 IP Threat Clusters</h2>
  {"<p style='color:#6b7280'>No IP clusters detected.</p>" if not correlation.get('ip_clusters') else f"""
  <table><tr><th>Source IP</th><th>Events</th><th>Attack Types</th><th>Risk</th></tr>{ip_rows}</table>"""}
</div>

<div class="card">
  <h2>⚠️ Threat Findings & Response Playbooks</h2>
  {"<p style='color:#6b7280'>No threats detected.</p>" if not anomalous else finding_rows}
</div>

</div>
</body>
</html>"""

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    return output_path


# ── Plain-text report ────────────────────────────────────────────────────────
def generate_text_report(findings, correlation, stats, sigma_rules, output_path):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    anomalous = [f for f in findings if f.get("is_anomalous")]
    lines = [
        "=" * 72,
        "  ThreatSight v2.0 — Security Detection Report",
        f"  Generated : {now}",
        f"  Author    : Krutika Jagdale",
        "=" * 72,
        "",
        "EXECUTIVE SUMMARY",
        "-" * 40,
        f"  Events analyzed   : {stats['total']}",
        f"  Threats detected  : {stats['anomalous']}",
        f"  Clean events      : {stats['clean']}",
        f"  Kill chain steps  : {len(correlation.get('kill_chain',[]))}",
        "",
    ]
    campaign = correlation.get("campaign")
    if campaign and campaign.get("detected"):
        lines += [
            f"  ⚠ CAMPAIGN DETECTED ({campaign.get('confidence','').upper()} confidence)",
            f"  {campaign.get('description','')}",
            f"  ACTION: {campaign.get('recommendation','')}",
            "",
        ]
    lines += ["RISK BREAKDOWN", "-" * 40]
    for lvl in ["critical","high","medium","low","none"]:
        count = stats.get("by_risk",{}).get(lvl,0)
        if count:
            lines.append(f"  {lvl.upper():<12}: {count}")
    lines += ["", "KILL CHAIN", "-" * 40]
    for step in correlation.get("kill_chain",[]):
        lines.append(f"  Step {step['step']:02d} | {step['tactic']:<25} | {step['attack_type']}")
    lines += ["", "THREAT FINDINGS", "-" * 40]
    for f in anomalous:
        lines += [
            f"\n  [{f.get('risk_level','?').upper()}] {f.get('attack_type','')} — Event {f.get('query_id','')}",
            f"  Time      : {f.get('timestamp','')}",
            f"  User      : {f.get('user','')} ({f.get('source_ip','')})",
            f"  Category  : {f.get('category','')}",
            f"  MITRE     : {', '.join(f.get('mitre_techniques',[]))}",
            f"  Reasoning : {f.get('reasoning','')}",
            f"  Rule      : {f.get('detection_rule','')}",
            "  Playbook  :",
        ]
        for step in get_playbook(f.get("attack_type","")):
            lines.append(f"    {step}")
    lines += ["", "", "SIGMA DETECTION RULES", "-" * 40, "", sigma_rules, "", "=" * 72]
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    return output_path


# ── JSON export for SIEM ─────────────────────────────────────────────────────
def generate_json_export(findings, correlation, stats, output_path):
    payload = {
        "meta": {
            "generated": datetime.now(timezone.utc).isoformat(),
            "tool": "ThreatSight v2.0",
            "author": "Krutika Jagdale",
        },
        "stats": stats,
        "correlation": correlation,
        "findings": findings,
    }
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return output_path
